config/routes.rb
Rails.application.routes.draw do

  root 'post#TOP'

  get 'user/new', to:"user#new" , as:"user_new"
  post "user/create" , to:"user#create" , as:"signin"
  get "user/show/:id" , to:"user#show" , as:"user_show"
  get "/login" , to:"session#login" , as:"login"
  post "/logedin" , to:"session#create" , as:"logedin"
  delete "/logout" , to:"session#logout" , as:"logout"

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get 'post/new', to:"post#new" , as:"post_new"
  post "post/create" , to:"post#create" , as:"post_create"
  get 'post/show/:id', to:"post#show" , as:"post_show"
  get "/edit/:id", to:"post#edit", as:"edit"
  patch "/update/:id" , to:"post#update" , as:"update"
  delete "delete/:id" , to:"post#delete" , as:"delete"
  get 'post_search', to:"post#search" , as:"post_search"
  get 'post/category/:id', to:"post#category" , as:"post_category"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
                                                                                      

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, class_name: "User", foreign_key: "user_id" , optional: true
    # TODO: user_idをPostに追加しないと関連付けが出来ない。
    belongs_to :category, class_name: "Category",foreign_key:"category_id"

    end

app/models/twitter_user.rb
class TwitterUser < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :post,class_name:"Post"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :display_categories

  def display_categories
    @categories = Category.all
end


end

app/controllers/category_controller.rb
class PostController < ApplicationController

def TOP
@post = Post.all
@post = Post.where.not(del_flag: 1)
@category = Category.all
end
#※del_flagが1のやつは表示しない！
     
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def TOP
   @post = Post.all
    @post = Post.where.not(del_flag: 1)
    @category = Category.all
    end
    #※del_flagが1のやつは表示しない！

  def new
    @post = Post.new
    @category = Category.all
  end

  
    def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
  end
end


  def show
    @post = Post.find_by(id:params[:id])
    @category = Category.find_by(id:params[:id])
  end

  def edit
    @post = Post.find_by(id:params[:id])
    @categories = Category.all
  end

  def update
    @post = Post.find_by(id:params[:id])
    if @post.update_attributes(post_params)
      redirect_to root_path
    end
  end

  def delete
    @post = Post.find_by(id:params[:id])
    if @post.del_flag = 1
      @post.save
      redirect_to root_path
  end
end

def search
  @post = Post.where(['title LIKE ? OR content LIKE ?', "%#{params[:search]}%","%#{params[:search]}%"])
  
  
end


def category
    @post = Post.where(category_id:params[:id]).where.not(del_flag: 1)
    @category = Category.find_by(id:params[:id])
end


  private
  def post_params
    params.require(:post).permit(:title , :content , :category_id)
  end

  

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def login
  end

  def create
    user = User.find_by(email:params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :login
    end
  end
  
  #def create
    #user = User.find_by(email:params[:session][:email])
    #if user &&
      #user.authenticate(params[:session][:password])
      #session[:user_id] = user.id
      #redirect_to root_path
    #else
      #render :login
    #end
  #end

  def logout
    session.delete(:user_id)
    redirect_to root_path
    end
    
end

app/controllers/twitter_sessions_controller.rb
class TwitterSessionsController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_show_path(@user)
    else
      render :new
    end
  end

#def create
   # @user = User.new(user_params)
    #if @user.save
      #redirect_to root_path
    #else
      #render :new
    #end
  #end

  def show
    @user = User.find_by(id:params[:id])
    @post = Post.all
    @post = Post.where.not(del_flag: 1)
    @category = Category.all
  end


  private
  def user_params
    params.require(:user).permit(:name, :email , :password , :pasword_confirmation , :twitter_account , :image_name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/session_helper.rb
module SessionHelper
        # 渡されたユーザーでログインする
        def log_in(user)
          session[:uid] = user.uid
        end
      
        # 現在ログイン中のユーザーを返す (いる場合)
        def current_user
          if session[:uid]
            @current_user ||= User.find_by(uid: session[:uid])
          end
        end
      
        # ユーザーがログインしていればtrue、その他ならfalseを返す
        def logged_in?
          !current_user.nil?
        end
      
        # 現在のユーザーをログアウトする
        def log_out
          session.delete(:uid)
          @current_user = nil
        end
end

app/helpers/twitter_sessions_helper.rb
module TwitterSessionsHelper
    class SessionsController < ApplicationController
        def create
          unless request.env['omniauth.auth'][:uid]
            flash[:danger] = '連携に失敗しました'
            redirect_to root_url
          end
          user_data = request.env['omniauth.auth']
          user = User.find_by(uid: user_data[:uid])
          if user
            log_in user
            flash[:success] = 'ログインしました'
            redirect_to root_url
          else
            new_user = User.new(
              uid: user_data[:uid],
              nickname: user_data[:info][:nickname],
              name: user_data[:info][:name],
              image: user_data[:info][:image],
            )
            if new_user.save
              log_in new_user
              flash[:success] = 'ユーザー登録成功'
            else
              flash[:danger] = '予期せぬエラーが発生しました'
            end
            redirect_to root_url
          end
        end
      
      
        def destroy
          log_out if logged_in?
          flash[:success] = 'ログアウトしました'
          redirect_to root_url
        end
      end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_function.html.erb
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">TOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

         
        <div class="d-flex">
        
        <%=form_tag(post_search_path , method: :get)do%>
        <input class="-control me-2" name = "search"type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
          </div>
        <%end%>

        <!--ユーザーがログイン状態のときのみ表示-->
        <%if session[:user_id] != nil%>
        <li class="nav-item">
          <%= link_to "新規投稿", post_new_path, class: 'nav-link' %>
        </li>
        </li>
      </ul>
      <div class="d-flex">
        <!--ユーザーがログイン状態のときのみ表示-->
        <%= link_to "マイページ", user_show_path(session[:user_id]), class: 'nav-link btn btn-outline-success' %>
      </div>
      <%else%>
      <div class="d-flex">
        <%= link_to "会員登録", user_new_path, class: 'nav-link btn btn-outline-success' %>
        <%= link_to "ログイン", login_path, class: 'nav-link btn btn-outline-success' %>
      </div>
      <% end %>
    </div>
  </div>
</nav>
   <!--ヘッダー（カテゴリー分け）-->
  <header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">TOP</a>
        </li>
        <%@categories.each do |c|%>
        <li class="nav-item">
        <%=link_to c.content , post_category_path(c.id), class: "nav-link"%>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html　lang="en">

<head>
  <title>HobbyApp</title>
  <%= csrf_meta_tags %>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= render 'layouts/function' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/function' %>

</html>      
    <%= yield %>
  </body>
</html>

<!--
      ユーザーがログイン状態のときのみ表示
        <li class="nav-item">
        <%if session[:user_id] != nil%>
          <a class="nav-link" href="/post/new">新規投稿</a>
           <%end%>
        </li>
        </li>
      </ul>

      <form class="d-flex">
      ユーザーがログイン状態のときのみ表示
       <%if session[:user_id] != nil%>
      <a class="nav-link" href="/user/show/:id"><button class="btn btn-outline-success" type="submit">マイページ</button></a>
       <%end%>

      <a class="nav-link" href="/user/new"><button class="btn btn-outline-success" type="submit">会員登録</button></a>
        <a class="nav-link" href="/login"><button class="btn btn-outline-success" type="submit">ログイン</button></a>
      </form>
    </div>
  </div>
</nav>
-->



<!--
      <%if session[:user_id] != nil%>
      <%=User.find(session[:user_id]).email%>
      <%=link_to "新規投稿", post_new_path%> 
      <%end%>


       <%if session[:user_id] != nil%>
      <%=link_to"新規投稿",post_new_path%>
      <%end%>
       

     -->

app/views/post/TOP.html.erb
<!--3つの特徴-->
<div class = container>
<div>
<h1 class= "text-center">〜Hobbyでできること〜</h1>
</div>
<div>
したいこと、やりたいことを見つけよう！<button type="button" class="btn btn-secondary btn-sm">探す🔍</button>
<%= image_tag 'hobby1.jpg', class: '' ,size: '200x150' %>
<%= image_tag 'hobby2.jpg', class: '' , size: '200x150'%>
<%= image_tag 'hobby3.jpg', class: '' , size: '200x150'%>
</div>

<!--コンテンツB-->

<p>各カテゴリ新着情報</p>
<%@categories.each do |c|%>
<p><%=c.content%></p>
<% @post.each do |post| %>
<%if post.del_flag != 1%>
<%if post.category_id == c.id%>
<div class="card" style="width: 18rem; background-color: yellow">
  <div class="card-body">
    <h5 class="card-title"><%= link_to(post.title,post_show_path(post.id)) %></h5><br/>
    </div>
    </div>
    <% end %>
<% end %>
<% end %>
<% end %>
</div>

<!--フッター--->
 <!--ヘッダー（カテゴリー分け）-->
  <div class = "footer">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
 
        <li class="nav-item">
          <a class="nav-link" href="#">Hobbyについて</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">ご利用ガイド</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#">利用規約</a>
        </li><br>
         <li class="nav-item">
          <a class="nav-link" href="#">ヘルプページ</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#">ご意見・ご要望</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#">お問い合わせ</a>
        </li><br>

        </li>
      </ul>
    </div>
  </div>
</nav>

 <div class="footer">
  <nav class="navbar navbar-expand-lg navbar-light bg-light text-center">
      <a class="navbar-brand" href="#">&copy; 20xx ○○ All Rights Reserved.</a>
    </div>
  </nav>



  </body>
</html>

app/views/post/category.html.erb
<div class = "category_show">
<h1><%=@category.content%></h1>
<%@post.each do |p|%>
<%=link_to p.title , post_show_path(p.id)%><br/>
<%end%>
</div>

app/views/post/edit.html.erb
<div class = "new">
<h1>投稿編集</h1>
<%if @post.del_flag != 1%>


<%=form_for(@post,url: update_path)do |f|%>
<%=f.label :title%>
<%=f.text_field :title , class: "form__txt"%>
<%=f.label :content%>
<%=f.text_field :content , class: "form__txt"%>
<div class="form_input">
  <%= f.label :category_id %>

    <select name="post[category_id]">
      <option>"カテゴリを選択してください"</option>
      <% @categories.each do |c| %>
      <% if @post.category_id == c.id %>
      <option value=<%= c.id %> selected><%= c.content %></option>
      <% else %>
      <option value=<%= c.id %>><%= c.content %></option>
      <% end %>
      <% end %>
    </select>


<%=f.submit "決定" %>
<%end%>
<%else%>
<%=このページは削除されました%>
<%end%>
</div>

app/views/post/new.html.erb
 <div class = "new">
<h1>新規投稿</h1>
 <%=form_for(@post, url: {controller: :post, action: :create})do |f|%>

<%=f.label :title%><br/>
<%=f.text_field :title , class: "form__txt"%><br/>

<%=f.label :content%><br/>
<%=f.text_area :content , class: "form__txt"%><br/>

<div class="form_input">
  <%= f.label :category_id %><br/>
  <!-- この下の部分の@categoryがないからmap nil error -->
  <%= f.collection_select :category_id, @category, :id, :content,
                                                            :include_blank => "カテゴリを選択してください" %>
</div>
<div class = "post_new">
<%=f.submit "投稿" %>
</div>

<%end%>
</div>
  </body>
</html>

app/views/post/search.html.erb
<%@post.each do |p|%>
<%= p.content%>
<%end%>

app/views/post/show.html.erb
 <div class = "show">
<h1>投稿詳細</h1>
<div class = "post_show">
<%if @post.del_flag != 1%>
<h4><%= @post.title%></h4><br/>
<p>内容：<%= @post.content%></p><br/>
<p>カテゴリー：<%= @post.category.content%></p><br/>

<%=link_to "編集" , edit_path%>
<%=link_to "削除" , delete_path(@post) , method: :delete%>
<%else%>
<%=このページは削除されました%>
<%end%>
</div>
</div>
  </body>
</html>

app/views/session/login.html.erb
<h1>ログイン</h1>

<%=form_for(:session,url:logedin_path)do |f|%>

<%=f.label :email%>
<%=f.text_field :email , class: "form__txt"%>

<%=f.label :password%>
<%=f.text_field :password , class: "form__txt"%>

<%=f.submit "ログイン" %>
<%end%>

<!--
<%=form_for(:session,url:logedin_path)do |f|%>

<%=f.label :name%>
<%=f.text_field :name , class: "form__txt"%>

<%=f.label :email%>
<%=f.text_field :email , class: "form__txt"%>

<%=f.label :password%>
<%=f.text_field :password , class: "form__txt"%>

<%=f.label :twitter_accoount%>
<%=f.text_field :twitter_account , class: "form__txt"%>

<%=f.label :image_name%>
<%=f.text_field :image_name , class: "form__txt"%>

<%=f.submit "ログイン" %>
<%end%>
-->

app/views/user/new.html.erb
<h1>会員登録</h1>

<%=form_for(@user,url:signin_path)do |f|%>

<%=f.label :email%>
<%=f.text_field :email , class: "form__txt"%>

<%=f.label :password%>
<%=f.text_field :password , class: "form__txt"%>

<%=f.label :password_confirmation%>
<%=f.text_field :password_confirmation , class: "form__txt"%>

<%=f.label :twitter_accoount%>
<%=f.text_field :twitter_account , class: "form__txt"%>

<%=f.label :image_name%>
<%=f.text_field :image_name , class: "form__txt"%>

<%=f.submit "登録" %>
<%end%>

<%if session[:user_id] != nil%>
<%=User.find(session[:user_id]).email%>
<%end%>

app/views/user/show.html.erb
<div class = container>
<h1 class= "text-center">マイページ</h1>

<div class= "my_page">
 <%if session[:user_id] != nil%>
<%=User.find(session[:user_id]).email%>が利用しています<br>

<ul class="shareList">
  <li class="shareList-item">
    <a class="icon icon-twitter" href="#" title="Twitter">
      <i class="fab fa-twitter"></i>
    </a>
  </li>
</ul>

<p>投稿</p>
<% @post.each do |post| %>
<%if post.del_flag != 1%>
<p>タイトル：<%= link_to(post.title,post_show_path(post.id)) %></p>
<% end %>
<% end %>

<div>
 <% if logged_in? %>
    <%= link_to 'ログアウト', logout_path %>
  <% else %>
    <a href="/auth/twitter">ログイン</a>
  <% end %>
  </div>

     <%=link_to "ヘルプ/お問い合わせ" , "#"%><br>
     <%=link_to "ガイドライン" , "#"%><br>
      <%=link_to "ログアウト" , logout_path, method: :delete%><br>
<%end%>
</div>
</div>